version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - backend-network
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf

  gin-go-backend:
    build: .
    container_name: "backend"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
