name: Lint Commit Messages
on:
  push:
    branches:
      - "*"
      - "*/*"
  pull_request:

jobs:
  commitlint:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5